// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/v2/pkg/seaweedfs (interfaces: Client)

// Package seaweedfs is a generated GoMock package.
package seaweedfs

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSeaweedFSClient is a mock of Client interface.
type MockSeaweedFSClient struct {
	ctrl     *gomock.Controller
	recorder *MockSeaweedFSClientMockRecorder
}

// MockSeaweedFSClientMockRecorder is the mock recorder for MockSeaweedFSClient.
type MockSeaweedFSClientMockRecorder struct {
	mock *MockSeaweedFSClient
}

// NewMockSeaweedFSClient creates a new mock instance.
func NewMockSeaweedFSClient(ctrl *gomock.Controller) *MockSeaweedFSClient {
	mock := &MockSeaweedFSClient{ctrl: ctrl}
	mock.recorder = &MockSeaweedFSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeaweedFSClient) EXPECT() *MockSeaweedFSClientMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockSeaweedFSClient) DeleteFile(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockSeaweedFSClientMockRecorder) DeleteFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockSeaweedFSClient)(nil).DeleteFile), arg0, arg1)
}

// DownloadFile mocks base method.
func (m *MockSeaweedFSClient) DownloadFile(arg0 context.Context, arg1 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockSeaweedFSClientMockRecorder) DownloadFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockSeaweedFSClient)(nil).DownloadFile), arg0, arg1)
}

// DownloadFileWithStream mocks base method.
func (m *MockSeaweedFSClient) DownloadFileWithStream(arg0 context.Context, arg1 string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFileWithStream", arg0, arg1)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFileWithStream indicates an expected call of DownloadFileWithStream.
func (mr *MockSeaweedFSClientMockRecorder) DownloadFileWithStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFileWithStream", reflect.TypeOf((*MockSeaweedFSClient)(nil).DownloadFileWithStream), arg0, arg1)
}

// HealthCheck mocks base method.
func (m *MockSeaweedFSClient) HealthCheck(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockSeaweedFSClientMockRecorder) HealthCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockSeaweedFSClient)(nil).HealthCheck), arg0)
}

// UploadFile mocks base method.
func (m *MockSeaweedFSClient) UploadFile(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockSeaweedFSClientMockRecorder) UploadFile(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockSeaweedFSClient)(nil).UploadFile), arg0, arg1, arg2)
}

// UploadFileWithTTL mocks base method.
func (m *MockSeaweedFSClient) UploadFileWithTTL(arg0 context.Context, arg1 string, arg2 []byte, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFileWithTTL", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFileWithTTL indicates an expected call of UploadFileWithTTL.
func (mr *MockSeaweedFSClientMockRecorder) UploadFileWithTTL(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFileWithTTL", reflect.TypeOf((*MockSeaweedFSClient)(nil).UploadFileWithTTL), arg0, arg1, arg2, arg3)
}
