#!/bin/bash

bold=$(tput bold 2>/dev/null || true)
reset=$(tput sgr0 2>/dev/null || true)

while read local_ref local_sha remote_ref remote_sha; do
    if [[ "$local_ref" =~ ^refs/heads/ ]]; then
        branch_name=$(echo "$local_ref" | sed 's|^refs/heads/||')

        if [[ ! "$branch_name" =~ ^(feature|fix|hotfix|docs|refactor|build|test)/.*$ ]]; then
            echo "${bold}Branch names must start with 'feature/', 'fix/', 'refactor/', 'docs/', 'test/' or 'hotfix/' followed by either a task id or feature name.${reset}"
            exit 1
        fi
    fi
done

exit 0
