#!/bin/bash

bold=$(tput bold 2>/dev/null || true)
reset=$(tput sgr0 2>/dev/null || true)

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ $branch == "main" || $branch == "develop" || $branch == release/* ]]; then
  echo "${bold}You can't commit directly to protected branches${reset}"
  exit 1
fi
