// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/v2/pkg/ports/cache (interfaces: SchemaCacheRepository)
//
// Generated by this command:
//
//	mockgen --destination=repository.mock.go --package=cache . SchemaCacheRepository
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/LerianStudio/fetcher/v2/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSchemaCacheRepository is a mock of SchemaCacheRepository interface.
type MockSchemaCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockSchemaCacheRepositoryMockRecorder is the mock recorder for MockSchemaCacheRepository.
type MockSchemaCacheRepositoryMockRecorder struct {
	mock *MockSchemaCacheRepository
}

// NewMockSchemaCacheRepository creates a new mock instance.
func NewMockSchemaCacheRepository(ctrl *gomock.Controller) *MockSchemaCacheRepository {
	mock := &MockSchemaCacheRepository{ctrl: ctrl}
	mock.recorder = &MockSchemaCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaCacheRepository) EXPECT() *MockSchemaCacheRepositoryMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockSchemaCacheRepository) Clear(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockSchemaCacheRepositoryMockRecorder) Clear(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Clear), ctx)
}

// Close mocks base method.
func (m *MockSchemaCacheRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSchemaCacheRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Close))
}

// Delete mocks base method.
func (m *MockSchemaCacheRepository) Delete(ctx context.Context, configName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, configName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSchemaCacheRepositoryMockRecorder) Delete(ctx, configName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Delete), ctx, configName)
}

// Get mocks base method.
func (m *MockSchemaCacheRepository) Get(ctx context.Context, configName string) (*model.DataSourceSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, configName)
	ret0, _ := ret[0].(*model.DataSourceSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSchemaCacheRepositoryMockRecorder) Get(ctx, configName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Get), ctx, configName)
}

// IsHealthy mocks base method.
func (m *MockSchemaCacheRepository) IsHealthy(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockSchemaCacheRepositoryMockRecorder) IsHealthy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockSchemaCacheRepository)(nil).IsHealthy), ctx)
}

// Set mocks base method.
func (m *MockSchemaCacheRepository) Set(ctx context.Context, configName string, schema *model.DataSourceSchema, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, configName, schema, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSchemaCacheRepositoryMockRecorder) Set(ctx, configName, schema, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Set), ctx, configName, schema, ttl)
}
