// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/mongodb (interfaces: Datasource)
//
// Generated by this command:
//
//	mockgen --destination=datasource.mongodb.mock.go --package=mongodb . Datasource
//

// Package mongodb is a generated GoMock package.
package mongodb

import (
	context "context"
	reflect "reflect"

	job "github.com/LerianStudio/fetcher/pkg/model/job"
	gomock "go.uber.org/mock/gomock"
)

// MockDatasource is a mock of Datasource interface.
type MockDatasource struct {
	ctrl     *gomock.Controller
	recorder *MockDatasourceMockRecorder
	isgomock struct{}
}

// MockDatasourceMockRecorder is the mock recorder for MockDatasource.
type MockDatasourceMockRecorder struct {
	mock *MockDatasource
}

// NewMockDatasource creates a new mock instance.
func NewMockDatasource(ctrl *gomock.Controller) *MockDatasource {
	mock := &MockDatasource{ctrl: ctrl}
	mock.recorder = &MockDatasourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatasource) EXPECT() *MockDatasourceMockRecorder {
	return m.recorder
}

// CloseConnection mocks base method.
func (m *MockDatasource) CloseConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockDatasourceMockRecorder) CloseConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockDatasource)(nil).CloseConnection), ctx)
}

// GetDatabaseSchema mocks base method.
func (m *MockDatasource) GetDatabaseSchema(ctx context.Context) ([]CollectionSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseSchema", ctx)
	ret0, _ := ret[0].([]CollectionSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseSchema indicates an expected call of GetDatabaseSchema.
func (mr *MockDatasourceMockRecorder) GetDatabaseSchema(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseSchema", reflect.TypeOf((*MockDatasource)(nil).GetDatabaseSchema), ctx)
}

// ListCollectionNames mocks base method.
func (m *MockDatasource) ListCollectionNames(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectionNames", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollectionNames indicates an expected call of ListCollectionNames.
func (mr *MockDatasourceMockRecorder) ListCollectionNames(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectionNames", reflect.TypeOf((*MockDatasource)(nil).ListCollectionNames), ctx)
}

// Query mocks base method.
func (m *MockDatasource) Query(ctx context.Context, collection string, fields []string, filter map[string][]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, collection, fields, filter)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDatasourceMockRecorder) Query(ctx, collection, fields, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDatasource)(nil).Query), ctx, collection, fields, filter)
}

// QueryWithAdvancedFilters mocks base method.
func (m *MockDatasource) QueryWithAdvancedFilters(ctx context.Context, collection string, fields []string, filter map[string]job.FilterCondition) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithAdvancedFilters", ctx, collection, fields, filter)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithAdvancedFilters indicates an expected call of QueryWithAdvancedFilters.
func (mr *MockDatasourceMockRecorder) QueryWithAdvancedFilters(ctx, collection, fields, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithAdvancedFilters", reflect.TypeOf((*MockDatasource)(nil).QueryWithAdvancedFilters), ctx, collection, fields, filter)
}
