// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/mongodb (interfaces: MongoClientProvider)

// Package mongodb is a generated GoMock package.
package mongodb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mongo "go.mongodb.org/mongo-driver/mongo"
)

// MockMongoClientProvider is a mock of MongoClientProvider interface.
type MockMongoClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMongoClientProviderMockRecorder
}

// MockMongoClientProviderMockRecorder is the mock recorder for MockMongoClientProvider.
type MockMongoClientProviderMockRecorder struct {
	mock *MockMongoClientProvider
}

// NewMockMongoClientProvider creates a new mock instance.
func NewMockMongoClientProvider(ctrl *gomock.Controller) *MockMongoClientProvider {
	mock := &MockMongoClientProvider{ctrl: ctrl}
	mock.recorder = &MockMongoClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoClientProvider) EXPECT() *MockMongoClientProviderMockRecorder {
	return m.recorder
}

// GetDB mocks base method.
func (m *MockMongoClientProvider) GetDB(arg0 context.Context) (*mongo.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB", arg0)
	ret0, _ := ret[0].(*mongo.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDB indicates an expected call of GetDB.
func (mr *MockMongoClientProviderMockRecorder) GetDB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockMongoClientProvider)(nil).GetDB), arg0)
}
