// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/mongodb (interfaces: MongoClientProvider)
//
// Generated by this command:
//
//	mockgen --destination=mongo_client_provider.mock.go --package=mongodb . MongoClientProvider
//

// Package mongodb is a generated GoMock package.
package mongodb

import (
	context "context"
	reflect "reflect"

	mongo "go.mongodb.org/mongo-driver/v2/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockMongoClientProvider is a mock of MongoClientProvider interface.
type MockMongoClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMongoClientProviderMockRecorder
	isgomock struct{}
}

// MockMongoClientProviderMockRecorder is the mock recorder for MockMongoClientProvider.
type MockMongoClientProviderMockRecorder struct {
	mock *MockMongoClientProvider
}

// NewMockMongoClientProvider creates a new mock instance.
func NewMockMongoClientProvider(ctrl *gomock.Controller) *MockMongoClientProvider {
	mock := &MockMongoClientProvider{ctrl: ctrl}
	mock.recorder = &MockMongoClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoClientProvider) EXPECT() *MockMongoClientProviderMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockMongoClientProvider) Client(ctx context.Context) (*mongo.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client", ctx)
	ret0, _ := ret[0].(*mongo.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Client indicates an expected call of Client.
func (mr *MockMongoClientProviderMockRecorder) Client(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockMongoClientProvider)(nil).Client), ctx)
}
