plugins:
  - path: "@semantic-release/commit-analyzer"
    preset: conventionalcommits
    parserOpts:
      noteKeywords:
        - "BREAKING CHANGE"
        - "BREAKING CHANGES"
    releaseRules:
      - type: feat
        release: patch
      - type: perf
        release: patch
      - type: build
        release: patch
      - type: chore
        release: patch
      - type: ci
        release: patch
      - type: test
        release: patch
      - type: fix
        release: patch
      - type: refactor
        release: patch
      - type: docs
        release: patch
      - breaking: true
        release: patch

  - path: "@semantic-release/release-notes-generator"
    preset: conventionalcommits

  - path: "@semantic-release/changelog"
    changelogFile: CHANGELOG.md

  - path: "@semantic-release/git"
    assets:
      - CHANGELOG.md
    message: "chore(release): ${nextRelease.version}\n\nChangelog atualizado."

  - path: "@semantic-release/github"
    assets:
      - path: CHANGELOG.md
        label: "Changelog"
    successComment: false
    failComment: false
    labels: []

branches:
  - name: main
  - name: develop
    prerelease: beta
  - name: release-candidate
    prerelease: rc
  - name: maintenance/v1.4.x
    range: 1.4.x
    channel: 1.4.x
