// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/mongodb/job (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=job.mongodb.mock.go --package=job . Repository
//

// Package job is a generated GoMock package.
package job

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/fetcher/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, job *model.Job) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, job)
}

// ExistsRunningByMappedFieldKey mocks base method.
func (m *MockRepository) ExistsRunningByMappedFieldKey(ctx context.Context, organizationID uuid.UUID, keyPattern string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsRunningByMappedFieldKey", ctx, organizationID, keyPattern)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsRunningByMappedFieldKey indicates an expected call of ExistsRunningByMappedFieldKey.
func (mr *MockRepositoryMockRecorder) ExistsRunningByMappedFieldKey(ctx, organizationID, keyPattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsRunningByMappedFieldKey", reflect.TypeOf((*MockRepository)(nil).ExistsRunningByMappedFieldKey), ctx, organizationID, keyPattern)
}

// FindActiveByRequestHash mocks base method.
func (m *MockRepository) FindActiveByRequestHash(ctx context.Context, organizationID uuid.UUID, requestHash string) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByRequestHash", ctx, organizationID, requestHash)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByRequestHash indicates an expected call of FindActiveByRequestHash.
func (mr *MockRepositoryMockRecorder) FindActiveByRequestHash(ctx, organizationID, requestHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByRequestHash", reflect.TypeOf((*MockRepository)(nil).FindActiveByRequestHash), ctx, organizationID, requestHash)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id, organizationID uuid.UUID) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, organizationID)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id, organizationID)
}

// FindByRequestHashWithinWindow mocks base method.
func (m *MockRepository) FindByRequestHashWithinWindow(ctx context.Context, organizationID uuid.UUID, requestHash string, windowMinutes int) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRequestHashWithinWindow", ctx, organizationID, requestHash, windowMinutes)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRequestHashWithinWindow indicates an expected call of FindByRequestHashWithinWindow.
func (mr *MockRepositoryMockRecorder) FindByRequestHashWithinWindow(ctx, organizationID, requestHash, windowMinutes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRequestHashWithinWindow", reflect.TypeOf((*MockRepository)(nil).FindByRequestHashWithinWindow), ctx, organizationID, requestHash, windowMinutes)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, filters *ListFilter) ([]*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, filters)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, job *model.Job) (*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, job)
	ret0, _ := ret[0].(*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, job)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, id, organizationID uuid.UUID, status model.JobStatus, resultPath, resultHMAC string, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, organizationID, status, resultPath, resultHMAC, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, id, organizationID, status, resultPath, resultHMAC, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, id, organizationID, status, resultPath, resultHMAC, metadata)
}
