// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/mongodb/job (interfaces: mongoDatabaseProvider)
//
// Generated by this command:
//
//	mockgen --destination=mock_db_provider_test.go --package=job . mongoDatabaseProvider
//

// Package job is a generated GoMock package.
package job

import (
	context "context"
	reflect "reflect"

	mongo "go.mongodb.org/mongo-driver/mongo"
	gomock "go.uber.org/mock/gomock"
)

// MockmongoDatabaseProvider is a mock of mongoDatabaseProvider interface.
type MockmongoDatabaseProvider struct {
	ctrl     *gomock.Controller
	recorder *MockmongoDatabaseProviderMockRecorder
	isgomock struct{}
}

// MockmongoDatabaseProviderMockRecorder is the mock recorder for MockmongoDatabaseProvider.
type MockmongoDatabaseProviderMockRecorder struct {
	mock *MockmongoDatabaseProvider
}

// NewMockmongoDatabaseProvider creates a new mock instance.
func NewMockmongoDatabaseProvider(ctrl *gomock.Controller) *MockmongoDatabaseProvider {
	mock := &MockmongoDatabaseProvider{ctrl: ctrl}
	mock.recorder = &MockmongoDatabaseProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmongoDatabaseProvider) EXPECT() *MockmongoDatabaseProviderMockRecorder {
	return m.recorder
}

// GetDB mocks base method.
func (m *MockmongoDatabaseProvider) GetDB(ctx context.Context) (*mongo.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB", ctx)
	ret0, _ := ret[0].(*mongo.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDB indicates an expected call of GetDB.
func (mr *MockmongoDatabaseProviderMockRecorder) GetDB(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockmongoDatabaseProvider)(nil).GetDB), ctx)
}
