// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/crypto (interfaces: Cryptor)
//
// Generated by this command:
//
//	mockgen --destination=crypto.mock.go --package=crypto . Cryptor
//

// Package crypto is a generated GoMock package.
package crypto

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCryptor is a mock of Cryptor interface.
type MockCryptor struct {
	ctrl     *gomock.Controller
	recorder *MockCryptorMockRecorder
	isgomock struct{}
}

// MockCryptorMockRecorder is the mock recorder for MockCryptor.
type MockCryptorMockRecorder struct {
	mock *MockCryptor
}

// NewMockCryptor creates a new mock instance.
func NewMockCryptor(ctrl *gomock.Controller) *MockCryptor {
	mock := &MockCryptor{ctrl: ctrl}
	mock.recorder = &MockCryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptor) EXPECT() *MockCryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockCryptor) Decrypt(ctx context.Context, cipherTextBase64, keyVersion string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, cipherTextBase64, keyVersion)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockCryptorMockRecorder) Decrypt(ctx, cipherTextBase64, keyVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockCryptor)(nil).Decrypt), ctx, cipherTextBase64, keyVersion)
}

// Encrypt mocks base method.
func (m *MockCryptor) Encrypt(ctx context.Context, plain string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", ctx, plain)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockCryptorMockRecorder) Encrypt(ctx, plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockCryptor)(nil).Encrypt), ctx, plain)
}

// KeyVersion mocks base method.
func (m *MockCryptor) KeyVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// KeyVersion indicates an expected call of KeyVersion.
func (mr *MockCryptorMockRecorder) KeyVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyVersion", reflect.TypeOf((*MockCryptor)(nil).KeyVersion))
}
