// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/crypto (interfaces: KeyDeriver)
//
// Generated by this command:
//
//	mockgen --destination=key_deriver.mock.go --package=crypto . KeyDeriver
//

// Package crypto is a generated GoMock package.
package crypto

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKeyDeriver is a mock of KeyDeriver interface.
type MockKeyDeriver struct {
	ctrl     *gomock.Controller
	recorder *MockKeyDeriverMockRecorder
	isgomock struct{}
}

// MockKeyDeriverMockRecorder is the mock recorder for MockKeyDeriver.
type MockKeyDeriverMockRecorder struct {
	mock *MockKeyDeriver
}

// NewMockKeyDeriver creates a new mock instance.
func NewMockKeyDeriver(ctrl *gomock.Controller) *MockKeyDeriver {
	mock := &MockKeyDeriver{ctrl: ctrl}
	mock.recorder = &MockKeyDeriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyDeriver) EXPECT() *MockKeyDeriverMockRecorder {
	return m.recorder
}

// DeriveKey mocks base method.
func (m *MockKeyDeriver) DeriveKey(context string, length int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeriveKey", context, length)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeriveKey indicates an expected call of DeriveKey.
func (mr *MockKeyDeriverMockRecorder) DeriveKey(context, length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeriveKey", reflect.TypeOf((*MockKeyDeriver)(nil).DeriveKey), context, length)
}

// GetCredentialKey mocks base method.
func (m *MockKeyDeriver) GetCredentialKey() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialKey")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetCredentialKey indicates an expected call of GetCredentialKey.
func (mr *MockKeyDeriverMockRecorder) GetCredentialKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialKey", reflect.TypeOf((*MockKeyDeriver)(nil).GetCredentialKey))
}

// GetExternalHMACKey mocks base method.
func (m *MockKeyDeriver) GetExternalHMACKey() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalHMACKey")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetExternalHMACKey indicates an expected call of GetExternalHMACKey.
func (mr *MockKeyDeriverMockRecorder) GetExternalHMACKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalHMACKey", reflect.TypeOf((*MockKeyDeriver)(nil).GetExternalHMACKey))
}

// GetInternalHMACKey mocks base method.
func (m *MockKeyDeriver) GetInternalHMACKey() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInternalHMACKey")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetInternalHMACKey indicates an expected call of GetInternalHMACKey.
func (mr *MockKeyDeriverMockRecorder) GetInternalHMACKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInternalHMACKey", reflect.TypeOf((*MockKeyDeriver)(nil).GetInternalHMACKey))
}
