// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/crypto (interfaces: Signer)
//
// Generated by this command:
//
//	mockgen --destination=signer.mock.go --package=crypto . Signer
//

// Package crypto is a generated GoMock package.
package crypto

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSigner is a mock of Signer interface.
type MockSigner struct {
	ctrl     *gomock.Controller
	recorder *MockSignerMockRecorder
	isgomock struct{}
}

// MockSignerMockRecorder is the mock recorder for MockSigner.
type MockSignerMockRecorder struct {
	mock *MockSigner
}

// NewMockSigner creates a new mock instance.
func NewMockSigner(ctrl *gomock.Controller) *MockSigner {
	mock := &MockSigner{ctrl: ctrl}
	mock.recorder = &MockSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSigner) EXPECT() *MockSignerMockRecorder {
	return m.recorder
}

// Sign mocks base method.
func (m *MockSigner) Sign(payload []byte) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", payload)
	ret0, _ := ret[0].(string)
	return ret0
}

// Sign indicates an expected call of Sign.
func (mr *MockSignerMockRecorder) Sign(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockSigner)(nil).Sign), payload)
}

// SignReader mocks base method.
func (m *MockSigner) SignReader(r io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignReader", r)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignReader indicates an expected call of SignReader.
func (mr *MockSignerMockRecorder) SignReader(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignReader", reflect.TypeOf((*MockSigner)(nil).SignReader), r)
}

// SignatureVersion mocks base method.
func (m *MockSigner) SignatureVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignatureVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// SignatureVersion indicates an expected call of SignatureVersion.
func (mr *MockSignerMockRecorder) SignatureVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignatureVersion", reflect.TypeOf((*MockSigner)(nil).SignatureVersion))
}

// Verify mocks base method.
func (m *MockSigner) Verify(payload []byte, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", payload, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockSignerMockRecorder) Verify(payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockSigner)(nil).Verify), payload, signature)
}
