// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/components/manager/internal/services/command (interfaces: ConnectionTester)

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/fetcher/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockConnectionTester is a mock of ConnectionTester interface.
type MockConnectionTester struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionTesterMockRecorder
}

// MockConnectionTesterMockRecorder is the mock recorder for MockConnectionTester.
type MockConnectionTesterMockRecorder struct {
	mock *MockConnectionTester
}

// NewMockConnectionTester creates a new mock instance.
func NewMockConnectionTester(ctrl *gomock.Controller) *MockConnectionTester {
	mock := &MockConnectionTester{ctrl: ctrl}
	mock.recorder = &MockConnectionTesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionTester) EXPECT() *MockConnectionTesterMockRecorder {
	return m.recorder
}

// TestConnection mocks base method.
func (m *MockConnectionTester) TestConnection(arg0 context.Context, arg1 *model.Connection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockConnectionTesterMockRecorder) TestConnection(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockConnectionTester)(nil).TestConnection), arg0, arg1)
}
