// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/components/manager/internal/adapters/cache (interfaces: SchemaCacheRepository)

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/LerianStudio/fetcher/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockSchemaCacheRepository is a mock of SchemaCacheRepository interface.
type MockSchemaCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaCacheRepositoryMockRecorder
}

// MockSchemaCacheRepositoryMockRecorder is the mock recorder for MockSchemaCacheRepository.
type MockSchemaCacheRepositoryMockRecorder struct {
	mock *MockSchemaCacheRepository
}

// NewMockSchemaCacheRepository creates a new mock instance.
func NewMockSchemaCacheRepository(ctrl *gomock.Controller) *MockSchemaCacheRepository {
	mock := &MockSchemaCacheRepository{ctrl: ctrl}
	mock.recorder = &MockSchemaCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaCacheRepository) EXPECT() *MockSchemaCacheRepositoryMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockSchemaCacheRepository) Clear(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockSchemaCacheRepositoryMockRecorder) Clear(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Clear), arg0)
}

// Close mocks base method.
func (m *MockSchemaCacheRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSchemaCacheRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Close))
}

// Delete mocks base method.
func (m *MockSchemaCacheRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSchemaCacheRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockSchemaCacheRepository) Get(arg0 context.Context, arg1 string) (*model.DataSourceSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*model.DataSourceSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSchemaCacheRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Get), arg0, arg1)
}

// IsHealthy mocks base method.
func (m *MockSchemaCacheRepository) IsHealthy(arg0 context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockSchemaCacheRepositoryMockRecorder) IsHealthy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockSchemaCacheRepository)(nil).IsHealthy), arg0)
}

// Set mocks base method.
func (m *MockSchemaCacheRepository) Set(arg0 context.Context, arg1 string, arg2 *model.DataSourceSchema, arg3 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSchemaCacheRepositoryMockRecorder) Set(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSchemaCacheRepository)(nil).Set), arg0, arg1, arg2, arg3)
}
