// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/rabbitmq (interfaces: Adapter)

// Package rabbitmq is a generated GoMock package.
package rabbitmq

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// CircuitBreakerState mocks base method.
func (m *MockAdapter) CircuitBreakerState() CircuitState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CircuitBreakerState")
	ret0, _ := ret[0].(CircuitState)
	return ret0
}

// CircuitBreakerState indicates an expected call of CircuitBreakerState.
func (mr *MockAdapterMockRecorder) CircuitBreakerState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CircuitBreakerState", reflect.TypeOf((*MockAdapter)(nil).CircuitBreakerState))
}

// ConsumerLoop mocks base method.
func (m *MockAdapter) ConsumerLoop(arg0 context.Context, arg1 string, arg2 int, arg3 func(context.Context, []byte, map[string]interface{}) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumerLoop", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumerLoop indicates an expected call of ConsumerLoop.
func (mr *MockAdapterMockRecorder) ConsumerLoop(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerLoop", reflect.TypeOf((*MockAdapter)(nil).ConsumerLoop), arg0, arg1, arg2, arg3)
}

// IsHealthy mocks base method.
func (m *MockAdapter) IsHealthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsHealthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsHealthy indicates an expected call of IsHealthy.
func (mr *MockAdapterMockRecorder) IsHealthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsHealthy", reflect.TypeOf((*MockAdapter)(nil).IsHealthy))
}

// ProducerDefault mocks base method.
func (m *MockAdapter) ProducerDefault(arg0 context.Context, arg1, arg2 string, arg3 []byte, arg4 *map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProducerDefault", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProducerDefault indicates an expected call of ProducerDefault.
func (mr *MockAdapterMockRecorder) ProducerDefault(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProducerDefault", reflect.TypeOf((*MockAdapter)(nil).ProducerDefault), arg0, arg1, arg2, arg3, arg4)
}

// Shutdown mocks base method.
func (m *MockAdapter) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockAdapterMockRecorder) Shutdown(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockAdapter)(nil).Shutdown), arg0)
}
