// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/resolver (interfaces: ConnectionResolver)
//
// Generated by this command:
//
//	mockgen --destination=resolver.mock.go --package=resolver . ConnectionResolver
//

// Package resolver is a generated GoMock package.
package resolver

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/fetcher/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionResolver is a mock of ConnectionResolver interface.
type MockConnectionResolver struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionResolverMockRecorder
	isgomock struct{}
}

// MockConnectionResolverMockRecorder is the mock recorder for MockConnectionResolver.
type MockConnectionResolverMockRecorder struct {
	mock *MockConnectionResolver
}

// NewMockConnectionResolver creates a new mock instance.
func NewMockConnectionResolver(ctrl *gomock.Controller) *MockConnectionResolver {
	mock := &MockConnectionResolver{ctrl: ctrl}
	mock.recorder = &MockConnectionResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionResolver) EXPECT() *MockConnectionResolverMockRecorder {
	return m.recorder
}

// IsInternalDatasource mocks base method.
func (m *MockConnectionResolver) IsInternalDatasource(configName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInternalDatasource", configName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInternalDatasource indicates an expected call of IsInternalDatasource.
func (mr *MockConnectionResolverMockRecorder) IsInternalDatasource(configName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInternalDatasource", reflect.TypeOf((*MockConnectionResolver)(nil).IsInternalDatasource), configName)
}

// ListInternalConnections mocks base method.
func (m *MockConnectionResolver) ListInternalConnections(ctx context.Context) ([]*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInternalConnections", ctx)
	ret0, _ := ret[0].([]*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInternalConnections indicates an expected call of ListInternalConnections.
func (mr *MockConnectionResolverMockRecorder) ListInternalConnections(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInternalConnections", reflect.TypeOf((*MockConnectionResolver)(nil).ListInternalConnections), ctx)
}

// ResolveConnections mocks base method.
func (m *MockConnectionResolver) ResolveConnections(ctx context.Context, configNames []string) ([]*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveConnections", ctx, configNames)
	ret0, _ := ret[0].([]*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveConnections indicates an expected call of ResolveConnections.
func (mr *MockConnectionResolverMockRecorder) ResolveConnections(ctx, configNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveConnections", reflect.TypeOf((*MockConnectionResolver)(nil).ResolveConnections), ctx, configNames)
}

// ResolveInternalByConfigName mocks base method.
func (m *MockConnectionResolver) ResolveInternalByConfigName(ctx context.Context, configName string) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveInternalByConfigName", ctx, configName)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveInternalByConfigName indicates an expected call of ResolveInternalByConfigName.
func (mr *MockConnectionResolverMockRecorder) ResolveInternalByConfigName(ctx, configName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveInternalByConfigName", reflect.TypeOf((*MockConnectionResolver)(nil).ResolveInternalByConfigName), ctx, configName)
}
