// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/v2/pkg/resolver (interfaces: TenantConfigProvider)
//
// Generated by this command:
//
//	mockgen --destination=tenant_config_provider.mock.go --package=resolver . TenantConfigProvider
//

// Package resolver is a generated GoMock package.
package resolver

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTenantConfigProvider is a mock of TenantConfigProvider interface.
type MockTenantConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTenantConfigProviderMockRecorder
	isgomock struct{}
}

// MockTenantConfigProviderMockRecorder is the mock recorder for MockTenantConfigProvider.
type MockTenantConfigProviderMockRecorder struct {
	mock *MockTenantConfigProvider
}

// NewMockTenantConfigProvider creates a new mock instance.
func NewMockTenantConfigProvider(ctrl *gomock.Controller) *MockTenantConfigProvider {
	mock := &MockTenantConfigProvider{ctrl: ctrl}
	mock.recorder = &MockTenantConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantConfigProvider) EXPECT() *MockTenantConfigProviderMockRecorder {
	return m.recorder
}

// GetServiceConnection mocks base method.
func (m *MockTenantConfigProvider) GetServiceConnection(ctx context.Context, tenantID, service, module string) (*ServiceConnectionConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceConnection", ctx, tenantID, service, module)
	ret0, _ := ret[0].(*ServiceConnectionConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceConnection indicates an expected call of GetServiceConnection.
func (mr *MockTenantConfigProviderMockRecorder) GetServiceConnection(ctx, tenantID, service, module any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceConnection", reflect.TypeOf((*MockTenantConfigProvider)(nil).GetServiceConnection), ctx, tenantID, service, module)
}
