// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/ports/connection (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=repository.mock.go --package=connection . Repository
//

// Package connection is a generated GoMock package.
package connection

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/LerianStudio/fetcher/pkg/model"
	http "github.com/LerianStudio/fetcher/pkg/net/http"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AssignProductName mocks base method.
func (m *MockRepository) AssignProductName(ctx context.Context, connectionID uuid.UUID, productName string) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignProductName", ctx, connectionID, productName)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignProductName indicates an expected call of AssignProductName.
func (mr *MockRepositoryMockRecorder) AssignProductName(ctx, connectionID, productName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignProductName", reflect.TypeOf((*MockRepository)(nil).AssignProductName), ctx, connectionID, productName)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, conn *model.Connection) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, conn)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, conn)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID, deletedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, deletedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id, deletedAt)
}

// FindByConfigNames mocks base method.
func (m *MockRepository) FindByConfigNames(ctx context.Context, configNames []string) ([]*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByConfigNames", ctx, configNames)
	ret0, _ := ret[0].([]*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByConfigNames indicates an expected call of FindByConfigNames.
func (mr *MockRepositoryMockRecorder) FindByConfigNames(ctx, configNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByConfigNames", reflect.TypeOf((*MockRepository)(nil).FindByConfigNames), ctx, configNames)
}

// FindByDatabaseName mocks base method.
func (m *MockRepository) FindByDatabaseName(ctx context.Context, databaseName string) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDatabaseName", ctx, databaseName)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDatabaseName indicates an expected call of FindByDatabaseName.
func (mr *MockRepositoryMockRecorder) FindByDatabaseName(ctx, databaseName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDatabaseName", reflect.TypeOf((*MockRepository)(nil).FindByDatabaseName), ctx, databaseName)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *MockRepository) FindByName(ctx context.Context, configName string) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, configName)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockRepositoryMockRecorder) FindByName(ctx, configName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockRepository)(nil).FindByName), ctx, configName)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, filters http.QueryHeader) ([]*model.Connection, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*model.Connection)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, filters)
}

// ListUnassigned mocks base method.
func (m *MockRepository) ListUnassigned(ctx context.Context, filters http.QueryHeader) ([]*model.Connection, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnassigned", ctx, filters)
	ret0, _ := ret[0].([]*model.Connection)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUnassigned indicates an expected call of ListUnassigned.
func (mr *MockRepositoryMockRecorder) ListUnassigned(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnassigned", reflect.TypeOf((*MockRepository)(nil).ListUnassigned), ctx, filters)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, conn *model.Connection) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conn)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, conn)
}
