// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/v2/pkg/ports/datasource (interfaces: CRMQueryable)
//
// Generated by this command:
//
//	mockgen --destination=crm.mock.go --package=datasource . CRMQueryable
//

// Package datasource is a generated GoMock package.
package datasource

import (
	context "context"
	reflect "reflect"

	job "github.com/LerianStudio/fetcher/v2/pkg/model/job"
	gomock "go.uber.org/mock/gomock"
)

// MockCRMQueryable is a mock of CRMQueryable interface.
type MockCRMQueryable struct {
	ctrl     *gomock.Controller
	recorder *MockCRMQueryableMockRecorder
	isgomock struct{}
}

// MockCRMQueryableMockRecorder is the mock recorder for MockCRMQueryable.
type MockCRMQueryableMockRecorder struct {
	mock *MockCRMQueryable
}

// NewMockCRMQueryable creates a new mock instance.
func NewMockCRMQueryable(ctrl *gomock.Controller) *MockCRMQueryable {
	mock := &MockCRMQueryable{ctrl: ctrl}
	mock.recorder = &MockCRMQueryableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCRMQueryable) EXPECT() *MockCRMQueryableMockRecorder {
	return m.recorder
}

// ListCollectionNames mocks base method.
func (m *MockCRMQueryable) ListCollectionNames(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectionNames", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollectionNames indicates an expected call of ListCollectionNames.
func (mr *MockCRMQueryableMockRecorder) ListCollectionNames(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectionNames", reflect.TypeOf((*MockCRMQueryable)(nil).ListCollectionNames), ctx)
}

// QueryCollection mocks base method.
func (m *MockCRMQueryable) QueryCollection(ctx context.Context, collection string, fields []string, filter map[string][]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCollection", ctx, collection, fields, filter)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCollection indicates an expected call of QueryCollection.
func (mr *MockCRMQueryableMockRecorder) QueryCollection(ctx, collection, fields, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCollection", reflect.TypeOf((*MockCRMQueryable)(nil).QueryCollection), ctx, collection, fields, filter)
}

// QueryCollectionWithAdvancedFilters mocks base method.
func (m *MockCRMQueryable) QueryCollectionWithAdvancedFilters(ctx context.Context, collection string, fields []string, filters map[string]job.FilterCondition) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCollectionWithAdvancedFilters", ctx, collection, fields, filters)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCollectionWithAdvancedFilters indicates an expected call of QueryCollectionWithAdvancedFilters.
func (mr *MockCRMQueryableMockRecorder) QueryCollectionWithAdvancedFilters(ctx, collection, fields, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCollectionWithAdvancedFilters", reflect.TypeOf((*MockCRMQueryable)(nil).QueryCollectionWithAdvancedFilters), ctx, collection, fields, filters)
}
