// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/model/datasource (interfaces: DataSource)

// Package datasource is a generated GoMock package.
package datasource

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/fetcher/pkg/model"
	job "github.com/LerianStudio/fetcher/pkg/model/job"
	log "github.com/LerianStudio/lib-commons/v2/commons/log"
	gomock "github.com/golang/mock/gomock"
)

// MockDataSource is a mock of DataSource interface.
type MockDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceMockRecorder
}

// MockDataSourceMockRecorder is the mock recorder for MockDataSource.
type MockDataSourceMockRecorder struct {
	mock *MockDataSource
}

// NewMockDataSource creates a new mock instance.
func NewMockDataSource(ctrl *gomock.Controller) *MockDataSource {
	mock := &MockDataSource{ctrl: ctrl}
	mock.recorder = &MockDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSource) EXPECT() *MockDataSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDataSource) Close(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDataSourceMockRecorder) Close(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDataSource)(nil).Close), arg0)
}

// Connect mocks base method.
func (m *MockDataSource) Connect(arg0 context.Context, arg1 log.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockDataSourceMockRecorder) Connect(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockDataSource)(nil).Connect), arg0, arg1)
}

// GetConfig mocks base method.
func (m *MockDataSource) GetConfig() DataSourceConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(DataSourceConfig)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockDataSourceMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockDataSource)(nil).GetConfig))
}

// GetSchemaInfo mocks base method.
func (m *MockDataSource) GetSchemaInfo(arg0 context.Context, arg1 []string) (*model.DataSourceSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchemaInfo", arg0, arg1)
	ret0, _ := ret[0].(*model.DataSourceSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchemaInfo indicates an expected call of GetSchemaInfo.
func (mr *MockDataSourceMockRecorder) GetSchemaInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchemaInfo", reflect.TypeOf((*MockDataSource)(nil).GetSchemaInfo), arg0, arg1)
}

// GetType mocks base method.
func (m *MockDataSource) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockDataSourceMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockDataSource)(nil).GetType))
}

// Query mocks base method.
func (m *MockDataSource) Query(arg0 context.Context, arg1 map[string][]string, arg2 map[string]map[string]job.FilterCondition, arg3 log.Logger) (map[string][]map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(map[string][]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDataSourceMockRecorder) Query(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDataSource)(nil).Query), arg0, arg1, arg2, arg3)
}
