// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/mongodb/connection/connection.mongodb.go

// Package connection is a generated GoMock package.
package connection

import (
	"context"
	"reflect"
	"time"

	"github.com/LerianStudio/fetcher/pkg/model"
	"github.com/LerianStudio/fetcher/pkg/net/http"
	"github.com/golang/mock/gomock"
	"github.com/google/uuid"
	"go.mongodb.org/mongo-driver/mongo"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, conn *model.Connection) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, conn)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, conn)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id, organizationID uuid.UUID, deletedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, organizationID, deletedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id, organizationID, deletedAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id, organizationID, deletedAt)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id, organizationID uuid.UUID) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, organizationID)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id, organizationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id, organizationID)
}

// FindByOrganizationAndDatabaseName mocks base method.
func (m *MockRepository) FindByOrganizationAndDatabaseName(ctx context.Context, organizationID uuid.UUID, databaseName string) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrganizationAndDatabaseName", ctx, organizationID, databaseName)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrganizationAndDatabaseName indicates an expected call of FindByOrganizationAndDatabaseName.
func (mr *MockRepositoryMockRecorder) FindByOrganizationAndDatabaseName(ctx, organizationID, databaseName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrganizationAndDatabaseName", reflect.TypeOf((*MockRepository)(nil).FindByOrganizationAndDatabaseName), ctx, organizationID, databaseName)
}

// FindByOrganizationAndName mocks base method.
func (m *MockRepository) FindByOrganizationAndName(ctx context.Context, organizationID uuid.UUID, configName string) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrganizationAndName", ctx, organizationID, configName)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrganizationAndName indicates an expected call of FindByOrganizationAndName.
func (mr *MockRepositoryMockRecorder) FindByOrganizationAndName(ctx, organizationID, configName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrganizationAndName", reflect.TypeOf((*MockRepository)(nil).FindByOrganizationAndName), ctx, organizationID, configName)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, organizationID uuid.UUID, filters http.QueryHeader) ([]*model.Connection, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, organizationID, filters)
	ret0, _ := ret[0].([]*model.Connection)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, organizationID, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, organizationID, filters)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, conn *model.Connection) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, conn)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, conn)
}

// FindByConfigNames mocks base method.
func (m *MockRepository) FindByConfigNames(ctx context.Context, organizationID uuid.UUID, configNames []string) ([]*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByConfigNames", ctx, organizationID, configNames)
	ret0, _ := ret[0].([]*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByConfigNames indicates an expected call of FindByConfigNames.
func (mr *MockRepositoryMockRecorder) FindByConfigNames(ctx, organizationID, configNames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByConfigNames", reflect.TypeOf((*MockRepository)(nil).FindByConfigNames), ctx, organizationID, configNames)
}

// ListUnassigned mocks base method.
func (m *MockRepository) ListUnassigned(ctx context.Context, organizationID uuid.UUID, filters http.QueryHeader) ([]*model.Connection, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnassigned", ctx, organizationID, filters)
	ret0, _ := ret[0].([]*model.Connection)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUnassigned indicates an expected call of ListUnassigned.
func (mr *MockRepositoryMockRecorder) ListUnassigned(ctx, organizationID, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnassigned", reflect.TypeOf((*MockRepository)(nil).ListUnassigned), ctx, organizationID, filters)
}

// AssignProduct mocks base method.
func (m *MockRepository) AssignProduct(ctx context.Context, connectionID, organizationID, productID uuid.UUID) (*model.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignProduct", ctx, connectionID, organizationID, productID)
	ret0, _ := ret[0].(*model.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignProduct indicates an expected call of AssignProduct.
func (mr *MockRepositoryMockRecorder) AssignProduct(ctx, connectionID, organizationID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignProduct", reflect.TypeOf((*MockRepository)(nil).AssignProduct), ctx, connectionID, organizationID, productID)
}

// CountByProduct mocks base method.
func (m *MockRepository) CountByProduct(ctx context.Context, organizationID, productID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByProduct", ctx, organizationID, productID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByProduct indicates an expected call of CountByProduct.
func (mr *MockRepositoryMockRecorder) CountByProduct(ctx, organizationID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByProduct", reflect.TypeOf((*MockRepository)(nil).CountByProduct), ctx, organizationID, productID)
}

// MockmongoDatabaseProvider is a mock of mongoDatabaseProvider interface.
type MockmongoDatabaseProvider struct {
	ctrl     *gomock.Controller
	recorder *MockmongoDatabaseProviderMockRecorder
}

// MockmongoDatabaseProviderMockRecorder is the mock recorder for MockmongoDatabaseProvider.
type MockmongoDatabaseProviderMockRecorder struct {
	mock *MockmongoDatabaseProvider
}

// NewMockmongoDatabaseProvider creates a new mock instance.
func NewMockmongoDatabaseProvider(ctrl *gomock.Controller) *MockmongoDatabaseProvider {
	mock := &MockmongoDatabaseProvider{ctrl: ctrl}
	mock.recorder = &MockmongoDatabaseProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmongoDatabaseProvider) EXPECT() *MockmongoDatabaseProviderMockRecorder {
	return m.recorder
}

// GetDB mocks base method.
func (m *MockmongoDatabaseProvider) GetDB(ctx context.Context) (*mongo.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB", ctx)
	ret0, _ := ret[0].(*mongo.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDB indicates an expected call of GetDB.
func (mr *MockmongoDatabaseProviderMockRecorder) GetDB(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockmongoDatabaseProvider)(nil).GetDB), ctx)
}
