// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/pkg/mongodb/connection (interfaces: Repository)
//
// Generated by this command:
//
// 	mockgen --destination=connection.mongodb.mock.go --package=connection . Repository
//

// Package connection is a generated GoMock package.
package connection

import (
	context "context"
	reflect "reflect"
	time "time"

	domainConn "github.com/LerianStudio/fetcher/pkg/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, connection *domainConn.Connection) (*domainConn.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, connection)
	ret0, _ := ret[0].(*domainConn.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, connection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, connection)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id, organizationID uuid.UUID, deletedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, organizationID, deletedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id, organizationID, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id, organizationID, deletedAt)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id, organizationID uuid.UUID) (*domainConn.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, organizationID)
	ret0, _ := ret[0].(*domainConn.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id, organizationID)
}

// FindByOrganizationAndName mocks base method.
func (m *MockRepository) FindByOrganizationAndName(ctx context.Context, organizationID uuid.UUID, configName string) (*domainConn.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrganizationAndName", ctx, organizationID, configName)
	ret0, _ := ret[0].(*domainConn.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrganizationAndName indicates an expected call of FindByOrganizationAndName.
func (mr *MockRepositoryMockRecorder) FindByOrganizationAndName(ctx, organizationID, configName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrganizationAndName", reflect.TypeOf((*MockRepository)(nil).FindByOrganizationAndName), ctx, organizationID, configName)
}

// FindByOrganizationAndDatabaseName mocks base method.
func (m *MockRepository) FindByOrganizationAndDatabaseName(ctx context.Context, organizationID uuid.UUID, databaseName string) (*domainConn.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrganizationAndDatabaseName", ctx, organizationID, databaseName)
	ret0, _ := ret[0].(*domainConn.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrganizationAndDatabaseName indicates an expected call of FindByOrganizationAndDatabaseName.
func (mr *MockRepositoryMockRecorder) FindByOrganizationAndDatabaseName(ctx, organizationID, databaseName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrganizationAndDatabaseName", reflect.TypeOf((*MockRepository)(nil).FindByOrganizationAndDatabaseName), ctx, organizationID, databaseName)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, filters *domainConn.ListFilterParams) ([]*domainConn.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*domainConn.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, filters)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, connection *domainConn.Connection) (*domainConn.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, connection)
	ret0, _ := ret[0].(*domainConn.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, connection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, connection)
}
