// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/components/manager/internal/services/query (interfaces: RateLimiterStore)

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRateLimiterStore is a mock of RateLimiterStore interface.
type MockRateLimiterStore struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterStoreMockRecorder
}

// MockRateLimiterStoreMockRecorder is the mock recorder for MockRateLimiterStore.
type MockRateLimiterStoreMockRecorder struct {
	mock *MockRateLimiterStore
}

// NewMockRateLimiterStore creates a new mock instance.
func NewMockRateLimiterStore(ctrl *gomock.Controller) *MockRateLimiterStore {
	mock := &MockRateLimiterStore{ctrl: ctrl}
	mock.recorder = &MockRateLimiterStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiterStore) EXPECT() *MockRateLimiterStoreMockRecorder {
	return m.recorder
}

// Take mocks base method.
func (m *MockRateLimiterStore) Take(arg0 context.Context, arg1 string) (uint64, uint64, uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(bool)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// Take indicates an expected call of Take.
func (mr *MockRateLimiterStoreMockRecorder) Take(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockRateLimiterStore)(nil).Take), arg0, arg1)
}
