//go:build chaos

// Package chaos contains chaos engineering tests for the Fetcher data extraction system.
// These tests verify system resilience under failure conditions using Toxiproxy
// to inject network faults such as latency, timeouts, and connection cuts.
//
// The tests require Docker to be running and use testcontainers to spin up:
//   - Core infrastructure: MongoDB, RabbitMQ, Redis, SeaweedFS (all with chaos proxies)
//   - Source database: PostgreSQL (with chaos proxy)
//   - Application containers: Manager API and Worker
//   - Chaos proxy: Toxiproxy for fault injection
//
// Environment variables:
//   - MANAGER_IMAGE: Docker image for Manager (default: fetcher-manager:latest)
//   - WORKER_IMAGE: Docker image for Worker (default: fetcher-worker:latest)
//   - E2E_SKIP_BUILD: If "true", use pre-built images instead of building (default: true)
package chaos

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/LerianStudio/fetcher/pkg/itestkit"
	"github.com/LerianStudio/fetcher/pkg/itestkit/addons/e2ekit"
	"github.com/LerianStudio/fetcher/pkg/itestkit/infra/postgres"
	e2eshared "github.com/LerianStudio/fetcher/tests/shared"
)

// Package-level variables hold the test infrastructure.
// These are initialized in TestMain and shared across all test functions.
var (
	// suite manages the lifecycle of all infrastructure containers.
	suite *itestkit.Suite
	// chaosInfra holds chaos-enabled MongoDB, RabbitMQ, Redis, and SeaweedFS.
	chaosInfra *ChaosInfra
	// postgresInfra is the PostgreSQL source database with chaos proxy enabled.
	postgresInfra *postgres.PostgresInfra
	// managerApp is the running Manager API container.
	managerApp *e2ekit.RunningApp
	// workerApp is the running Worker container.
	workerApp *e2ekit.RunningApp
	// apiClient is the HTTP client for the Manager API.
	apiClient *e2eshared.ManagerClient
	// amqpURL is the RabbitMQ connection URL for queue operations.
	amqpURL string

	// Proxy names for chaos injection.
	// These names must match the proxy names generated by itestkit when EnableProxy: true.
	// Format: <prefix>-<infra-name> where prefix is "mongo", "amqp", "redis", "pg", etc.
	mongoProxy    = "mongo-fetcher-chaos"
	rabbitProxy   = "amqp-fetcher-chaos"
	redisProxy    = "redis-fetcher-chaos"
	seaweedProxy  = "seaweed-fetcher-chaos"
	postgresProxy = "pg-source"
)

// TestMain is the entry point for chaos tests. It sets up all infrastructure before
// running tests and tears everything down afterward, regardless of test outcomes.
// The setup has a 10-minute timeout to allow for container startup and initialization.
func TestMain(m *testing.M) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()

	var code int
	defer func() {
		teardown(ctx)
		os.Exit(code)
	}()

	if err := setup(ctx); err != nil {
		log.Fatalf("Chaos test setup failed: %v", err)
	}

	code = m.Run()
}

// setup initializes all test infrastructure in the correct order.
// It creates containers for databases, message broker, cache, and file storage,
// all with chaos proxies enabled for fault injection, then starts the Manager
// and Worker application containers.
func setup(ctx context.Context) error {
	log.Println("Starting chaos test infrastructure...")

	// 1. Create chaos-enabled core infrastructure
	chaosInfra = NewChaosInfra()

	// 2. Create PostgreSQL source database with proxy enabled for chaos injection
	postgresInfra = postgres.NewPostgresInfra(postgres.PostgresConfig{
		Name:        "source",
		Database:    "testdb",
		Username:    e2eshared.SourceDBUsername,
		Password:    e2eshared.SourceDBPassword,
		EnableProxy: true,
		Options: []postgres.PostgresOption{
			postgres.WithPGInitFile(fixturesPath("postgres_init.sql"), "init.sql"),
		},
	})

	// 3. Build itestkit suite with chaos enabled
	var err error
	suite, err = itestkit.New(nil).
		WithChaos(itestkit.ChaosConfig{Enabled: true}).
		WithInfras(chaosInfra.Infras()...).
		WithInfra(postgresInfra).
		Build(ctx)
	if err != nil {
		return fmt.Errorf("build suite: %w", err)
	}

	// 4. Create proxies for chaos injection
	if err := createChaosProxies(ctx); err != nil {
		return fmt.Errorf("create chaos proxies: %w", err)
	}

	// 5. Build app environment using proxied endpoints
	appEnv, err := buildProxiedAppEnv()
	if err != nil {
		return fmt.Errorf("build proxied app env: %w", err)
	}

	// Store AMQP URL for queuekit (using proxy)
	amqpURL = appEnv.RabbitAMQPURL()

	// 6. Start Manager container
	log.Println("Starting Manager container...")
	managerApp, err = e2eshared.StartManager(nil, ctx, appEnv.ToAppEnv(), e2eshared.AppStartConfig{
		Image:     managerImage(),
		SkipBuild: skipBuild(),
	})
	if err != nil {
		return fmt.Errorf("start manager: %w", err)
	}

	// 7. Pre-create the object-storage bucket so the Worker's startup
	// self-probe (Gate 7 of ring:dev-readyz) can satisfy its s3 HeadBucket
	// check. Without this, /health stays 503 forever and StartWorker's
	// WaitHTTP /health gate times out. We hit SeaweedFS's host-mapped
	// proxy port — at setup time no toxics are active, so the proxy is
	// transparent and the bucket lands on the real SeaweedFS.
	if err := ensureChaosBucket(ctx, appEnv.ToAppEnv()); err != nil {
		return fmt.Errorf("ensure chaos bucket: %w", err)
	}

	// 8. Start Worker container
	log.Println("Starting Worker container...")
	workerApp, err = e2eshared.StartWorker(nil, ctx, appEnv.ToAppEnv(), e2eshared.AppStartConfig{
		Image:     workerImage(),
		SkipBuild: skipBuild(),
	})
	if err != nil {
		return fmt.Errorf("start worker: %w", err)
	}

	// 8. Create API client
	apiClient = e2eshared.NewClientFromApp(managerApp)

	log.Println("Chaos test infrastructure ready")
	return nil
}

// teardown stops and removes all test containers in reverse order.
// It's called from TestMain's defer to ensure cleanup happens even if tests panic.
func teardown(ctx context.Context) {
	log.Println("Tearing down chaos test infrastructure...")

	if workerApp != nil {
		_ = workerApp.Container.Terminate(ctx)
	}
	if managerApp != nil {
		_ = managerApp.Container.Terminate(ctx)
	}
	if suite != nil {
		_ = suite.Terminate(ctx)
	}
}

// createChaosProxies logs the available chaos proxies.
// All infrastructure components now have EnableProxy: true and create proxies automatically
// during their Start() method. This function only logs the available proxies for debugging.
func createChaosProxies(_ context.Context) error {
	chaos := suite.Chaos()
	if chaos == nil {
		return fmt.Errorf("chaos interface not available")
	}

	// All proxies are now created automatically by infrastructure with EnableProxy: true
	log.Printf("Chaos proxies available: %s, %s, %s, %s, %s",
		mongoProxy, rabbitProxy, redisProxy, postgresProxy, seaweedProxy)
	return nil
}

// managerImage returns the Docker image to use for the Manager container.
// Reads from MANAGER_IMAGE env var, defaulting to "fetcher-manager:latest".
func managerImage() string {
	if img := os.Getenv("MANAGER_IMAGE"); img != "" {
		return img
	}
	return "fetcher-manager:latest"
}

// workerImage returns the Docker image to use for the Worker container.
// Reads from WORKER_IMAGE env var, defaulting to "fetcher-worker:latest".
func workerImage() string {
	if img := os.Getenv("WORKER_IMAGE"); img != "" {
		return img
	}
	return "fetcher-worker:latest"
}

// skipBuild returns whether to skip building Docker images.
// If true, uses pre-built images; if false, builds from Dockerfile.
// Reads from E2E_SKIP_BUILD env var, defaulting to true.
func skipBuild() bool {
	if value := os.Getenv("E2E_SKIP_BUILD"); value != "" {
		return value == "true"
	}
	return true
}

// fixturesPath returns the absolute path to a fixture file in tests/shared/fixtures.
func fixturesPath(name string) string {
	return filepath.Join(e2ekit.ProjectRoot(), "tests", "shared", "fixtures", name)
}

// ensureChaosBucket pre-creates the configured object-storage bucket on the
// host-mapped SeaweedFS endpoint so the Worker's startup self-probe finds it.
// Mirrors the e2e suite's ensureStorageBucket — same rationale, different
// SeaweedFS handle (chaosInfra vs coreInfra).
//
// Setup-time call: no toxics are active yet, so the SeaweedFS proxy is a
// transparent pass-through and the CreateBucket request lands on the real
// SeaweedFS Filer.
func ensureChaosBucket(ctx context.Context, env *e2eshared.AppEnv) error {
	endpoint, err := chaosInfra.SeaweedFS.URL()
	if err != nil {
		return fmt.Errorf("resolve seaweedfs URL: %w", err)
	}

	log.Printf("Ensuring chaos object-storage bucket %q on %s", env.StorageBucket(), endpoint)

	return e2eshared.EnsureS3BucketAtHost(ctx, endpoint, env.StorageBucket(), "any", "any")
}
