// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/v2/pkg/ports/messaging (interfaces: MessagePublisher)
//
// Generated by this command:
//
//	mockgen --destination=publisher.mock.go --package=messaging . MessagePublisher
//

// Package messaging is a generated GoMock package.
package messaging

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMessagePublisher is a mock of MessagePublisher interface.
type MockMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePublisherMockRecorder
	isgomock struct{}
}

// MockMessagePublisherMockRecorder is the mock recorder for MockMessagePublisher.
type MockMessagePublisherMockRecorder struct {
	mock *MockMessagePublisher
}

// NewMockMessagePublisher creates a new mock instance.
func NewMockMessagePublisher(ctrl *gomock.Controller) *MockMessagePublisher {
	mock := &MockMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePublisher) EXPECT() *MockMessagePublisherMockRecorder {
	return m.recorder
}

// ProducerDefault mocks base method.
func (m *MockMessagePublisher) ProducerDefault(ctx context.Context, exchange, key string, queueMessage []byte, header *map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProducerDefault", ctx, exchange, key, queueMessage, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProducerDefault indicates an expected call of ProducerDefault.
func (mr *MockMessagePublisherMockRecorder) ProducerDefault(ctx, exchange, key, queueMessage, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProducerDefault", reflect.TypeOf((*MockMessagePublisher)(nil).ProducerDefault), ctx, exchange, key, queueMessage, header)
}
