// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/fetcher/v2/components/worker/internal/adapters/rabbitmq (interfaces: PublisherRepository)
//
// Generated by this command:
//
//	mockgen --destination=publisher.mock.go --package=rabbitmq . PublisherRepository
//

// Package rabbitmq is a generated GoMock package.
package rabbitmq

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPublisherRepository is a mock of PublisherRepository interface.
type MockPublisherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherRepositoryMockRecorder
	isgomock struct{}
}

// MockPublisherRepositoryMockRecorder is the mock recorder for MockPublisherRepository.
type MockPublisherRepositoryMockRecorder struct {
	mock *MockPublisherRepository
}

// NewMockPublisherRepository creates a new mock instance.
func NewMockPublisherRepository(ctrl *gomock.Controller) *MockPublisherRepository {
	mock := &MockPublisherRepository{ctrl: ctrl}
	mock.recorder = &MockPublisherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisherRepository) EXPECT() *MockPublisherRepositoryMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisherRepository) Publish(ctx context.Context, exchange, routingKey string, body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, exchange, routingKey, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherRepositoryMockRecorder) Publish(ctx, exchange, routingKey, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisherRepository)(nil).Publish), ctx, exchange, routingKey, body)
}

// Shutdown mocks base method.
func (m *MockPublisherRepository) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockPublisherRepositoryMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockPublisherRepository)(nil).Shutdown), ctx)
}
