name: PR Validation

on:
  pull_request:
    branches: [develop, release-candidate, main]
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  actions: read
  contents: read
  id-token: write
  issues: write
  pull-requests: write
  security-events: write

jobs:
  validate:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/go-pr-validation.yml@v1.36.4
    with:
      pr_title_scopes: |
        manager
        worker
        infra
        pkg
        scripts
        deps
        ci
        docs
        tests
        migrations
      go_version: "1.26.4"
      golangci_lint_version: "v2.6.2"
      app_name_prefix: "fetcher"
      filter_paths: |
        components/manager
        components/worker
      go_private_modules: "github.com/LerianStudio/*"
      ignore_file: ".trivyignore"
      shared_paths: |
        go.mod
        go.sum
        components/
        pkg/
        Makefile
      dockerfile_path: "components/manager/Dockerfile"
    secrets: inherit
