name: Release

on:
  push:
    branches: [develop, release-candidate, main]
    tags: ['**']

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  pipeline:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/go-release.yml@v1.36.0
    with:
      enable_changelog: ${{ github.ref == 'refs/heads/main' }}
      app_name_prefix: "fetcher"
      enable_gitops_artifacts: true
      filter_paths: |
        components/manager
        components/worker
      shared_paths: |
        go.mod
        go.sum
        pkg/
        Makefile
      enable_helm_dispatch: true
      helm_chart: "fetcher"
      helm_values_key_mappings: '{"fetcher-manager": "manager", "fetcher-worker": "worker"}'
      gitops_yaml_key_mappings: '{"fetcher-manager.tag": ".manager.image.tag", "fetcher-worker.tag": ".worker.image.tag"}'
    secrets: inherit
